# Generated by Django 3.2.8 on 2021-10-09 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresaCliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('celular', models.PositiveIntegerField(verbose_name='Celular')),
                ('email', models.EmailField(max_length=254)),
                ('empresa_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresaCliente.empresacliente')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
