# Generated by Django 3.2.8 on 2021-10-10 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresaCliente', '0004_auto_20211010_2133'),
        ('contacto', '0003_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='celular',
            field=models.BigIntegerField(verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='empresa_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresaCliente.empresacliente', verbose_name='Empresa cliente'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
    ]
