# Generated by Django 3.2.8 on 2021-10-09 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresaCliente', '0002_alter_empresacliente_email'),
        ('contacto', '0002_alter_contacto_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(max_length=100, verbose_name='UUID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la oportunidad de negocio')),
                ('monto', models.PositiveIntegerField(verbose_name='Monto total de la oportunidad')),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('ganada', 'Ganada'), ('no_ganada', 'No ganada'), ('cancelada', 'Cancelada (Descartada)')], default='en_proceso', max_length=100, verbose_name='Estado')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacto.contacto')),
                ('empresa_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresaCliente.empresacliente')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
