# Generated by Django 3.2.8 on 2021-10-10 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacto', '0004_auto_20211010_2133'),
        ('empresaCliente', '0004_auto_20211010_2133'),
        ('oportunidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='consecutivo',
            field=models.IntegerField(default=0, verbose_name='Consecutivo'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacto.contacto', verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='empresa_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresaCliente.empresacliente', verbose_name='Empresa cliente'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total de la oportunidad'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
    ]
