# Generated by Django 3.2.8 on 2021-10-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidad', '0002_auto_20211010_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Ganada', 'Ganada'), ('No ganada', 'No ganada'), ('Cancelada', 'Cancelada (Descartada)')], default='en_proceso', max_length=100, verbose_name='Estado'),
        ),
    ]
