# Generated by Django 3.2.8 on 2021-10-09 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la empresa')),
                ('nombre_comercial', models.CharField(max_length=100, verbose_name='Nombre comercial de la empresa')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254)),
                ('sitio_web', models.URLField()),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('estado', models.CharField(max_length=100, verbose_name='Departamento')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
