# Generated by Django 3.2.8 on 2021-10-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaCliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresacliente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
