# Generated by Django 3.2.8 on 2021-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaCliente', '0002_alter_empresacliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresacliente',
            name='telefono',
            field=models.BigIntegerField(verbose_name='Teléfono'),
        ),
    ]
