# Generated by Django 3.2.8 on 2021-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.BigIntegerField(verbose_name='Teléfono'),
        ),
    ]
