# Generated by Django 3.2.8 on 2021-10-10 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0002_auto_20211009_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='sitio_web',
            field=models.URLField(verbose_name='Sitio Web'),
        ),
    ]
